### ISSUE TITLE
I'm not sure how to proceed from the Set variables step

### ISSUE THREAD

**Issue by MelvinDRM** [jamstooks/django-acme-challenge#3]
Hello,

I'm new at this Django+Let's Encrypt thing.

You say that I just set two variables, ACME_CHALLENGE_URL_SLUG and ACME_CHALLENGE_TEMPLATE_CONTENT and then http://your-domain-name/.well-known/acme-challenge/ACME_CHALLENGE_URL_SLUG will then serve the value of ACME_CHALLENGE_TEMPLATE_CONTENT for validation. Also you say that you prefer to set them as env variables.

What does that mean? How else can be set (since the acme challenge changes its string everytime I try to generate the certificate)?

I followed your steps and set the variables like this:

ACME_CHALLENGE_URL_SLUG = os.getenv('ACME_CHALLENGE_URL_SLUG')
ACME_CHALLENGE_TEMPLATE_CONTENT = os.getenv('ACME_CHALLENGE_TEMPLATE_CONTENT')

But, clearly, is not working. I'm missing something and Saint Google has not been helpful. Can you guide me on this?

Thanks in advance

**Comment by jamstooks** [comment]
Hi @MelvinDRM,

Are your environment variables set up properly? These are environment variables on the system, not just django settings variables...

If you're using linux...

Confirm they're set properly with:

    echo $ACME_CHALLENGE_URL_SLUG
    echo $ACME_CHALLENGE_TEMPLATE_CONTENT

If they aren't, you'll need to set them:

    export ACME_CHALLENGE_URL_SLUG="yourslugvaluehere"
    export ACME_CHALLENGE_TEMPLATE_CONTENT="yourlongercontentvaluehere"

**Comment by jamstooks** [comment]
Just to follow up:

> What does that mean? How else can be set (since the acme challenge changes its string everytime I try to generate the certificate)?

I recommend environment variables because it's easier to change environment variables than change the code whenever you need to. But, you can still hard-code the values in your settings.py if you'd prefer that...

I'm going to close this issue as it doesn't seem to be a bug, but please feel free to reopen if you need some more help.

**Comment by diegolpedro** [comment]
Hi jamstooks, what do you mean with setting the variables? Correct me if I am wrong, but both variables are generated on runtime, with certbot. How can I set them before?
Thanks for your help.

**Comment by jamstooks** [comment]
@diegolpedro - Those two variables are just used to validate your server with Let's Encrypt and should only be generated once when creating the initial certificate... not at your application's runtime.

As per [the instructions](https://certbot.eff.org/docs/using.html#manual):
> The http challenge will ask you to place a file with a specific name and specific content in the `/.well-known/acme-challenge/` directory directly in the top-level directory (“web root”) containing the files served by your webserver.

Note: depending on your server config, you may not need to use this manual process. [There are plugins](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins) for several platforms at this point.
